# Configuración del sitio web
title: "Black Offset"
description: ""
author: "Security Research Team"
url: "https://agustedone.github.io"
baseurl: "/sec-blog"

# Configuración de Jekyll
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Configuración de posts
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/page:num/"

# Configuración de construcción
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# Configuración de colecciones
collections:
  advisories:
    output: true
    permalink: /advisories/:name/

# Configuración social (opcional)
github_username: agustedone
twitter_username: your-twitter

# Configuración de tema
remote_theme: pages-themes/minimal@v0.2.0 